// jobData.js

const jobData = [
    {
      id: 1,
      companyLogo: '../src/assets/logos/epic-hire-logo.png',
      companyName: 'Epic Hire',
      jobTitle: 'Frontend Intern',
      experienceLevel: 'Internship',
      location: 'Raleigh, NC',
      remoteType: 'Hybrid',
      postedDate: '2023-09-28',
      status: 'Interview',
    },
    {
      id: 2,
      companyLogo: '../src/assets/logos/google-logo.webp',
      companyName: 'Google',
      jobTitle: 'Backend Developer',
      experienceLevel: 'Internship',
      location: 'New York, NY',
      remoteType: 'Remote',
      postedDate: '2023-10-01',
      status: 'Applied',
    },
    {
      id: 3,
      companyLogo: '../src/assets/logos/meta-logo.png',
      companyName: 'Meta',
      jobTitle: 'UI/UX Designer',
      experienceLevel: 'Senior',
      location: 'Austin, TX',
      remoteType: 'Hybrid',
      postedDate: '2023-09-25',
      status: null,
    },
    {
      id: 4,
      companyLogo: '../src/assets/logos/netflix-logo.png',
      companyName: 'Netflix',
      jobTitle: 'Back-End Developer',
      experienceLevel: 'Entry-Level',
      location: 'Seattle, WA',
      remoteType: 'Remote',
      postedDate: '2023-10-02',
      status: null,
    },
    {
      id: 5,
      companyLogo: '../src/assets/logos/fidelity-logo.png',
      companyName: 'Fidelity',
      jobTitle: 'Data Analyst',
      experienceLevel: 'Mid-Level',
      location: 'Chicago, IL',
      remoteType: 'In-Person',
      postedDate: '2023-09-30',
      status: null,
    },
    {
      id: 6,
      companyLogo: '../src/assets/logos/red-hat-logo.svg',
      companyName: 'Red Hat',
      jobTitle: 'Product Manager',
      experienceLevel: 'Senior',
      location: 'Boston, MA',
      remoteType: 'Hybrid',
      postedDate: '2023-09-27',
      status: null,
    },
    {
      id: 7,
      companyLogo: '../src/assets/logos/tesla-logo.png',
      companyName: 'Tesla',
      jobTitle: 'Machine Learning Engineer',
      experienceLevel: 'Junior',
      location: 'Detroit, MI',
      remoteType: 'Remote',
      postedDate: '2023-10-03',
      status: null,
    },
    {
      id: 8,
      companyLogo: '../src/assets/logos/pinterest-logo.png',
      companyName: 'Pinterest',
      jobTitle: 'Systems Analyst',
      experienceLevel: 'Mid-Level',
      location: 'Denver, CO',
      remoteType: 'In-Person',
      postedDate: '2023-09-29',
      status: null,
    },
    {
      id: 9,
      companyLogo: '../src/assets/logos/amazon-logo.webp',
      companyName: 'Amazon',
      jobTitle: 'DevOps Engineer',
      experienceLevel: 'Senior',
      location: 'Atlanta, GA',
      remoteType: 'Hybrid',
      postedDate: '2023-09-26',
      status: null,
    },
    {
      id: 10,
      companyLogo: '../src/assets/logos/apple-logo.png',
      companyName: 'Apple',
      jobTitle: 'Software Engineer',
      experienceLevel: 'Entry-Level',
      location: 'Houston, TX',
      remoteType: 'Remote',
      postedDate: '2023-10-04',
      status: null,
    },
  ];
  
  export default jobData;
  